### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by 3kh0** [01f2/01f2.github.i0#1]
Hello!

I was just wondering what are you doing with my code? My systems have detected that your code here matches my code in my retro bowl project. I just want to know if you need help with improving my project!

Looking forward to talking with you!

Echo :)

**Comment by 01f2** [comment]
oh sorry, I was using your code as a part of my [games website project](https://github.com/01f2/games), it works very well.

**Comment by 3kh0** [comment]
Yes, but they are my games and I do not want them on other sites. You did not say on the site that I made them.
